keycloak-config:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}

oidc:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}
  token_url: ${TOKEN_URL}
  logout_url: ${LOGOUT_URL}
  issuer_url: ${ISSUER_URL}
  jwks_url: ${JWKS_URL}